id: IAB33BEA1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-31T20:07:06+00:00'
last_modified: '2022-06-08T12:34:41.634873+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ929
  title: སྡེབ་སྦྱོར་རྣམས་ཀྱི་མཚན་ཉིད་ཐོས་པས་ཆུབ་པ་
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    A42F:
      image_group_id: I1CZ1006
      title: ''
      total_pages: 28
      order: 1
      base_file: A42F.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
