id: P009651
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W1CZ929
  title: སྡེབ་སྦྱོར་རྣམས་ཀྱི་མཚན་ཉིད་ཐོས་པས་ཆུབ་པ་
  author: ''
  volumes:
    bc97e1a5f7d7489aa61ca7f662eb1b06:
      image_group_id: I1CZ1006
      title: ''
      volume_number: 1
      total_pages: 28
      base_file: v001.txt
